% Script

% Estimate the frequencies of the tone generated by pressing the 1 button on a telephone keypad.
% The number 1 produces a tone with frequencies 697 and 1209 Hz.
% Generate 205 samples of the tone with a sample rate of 8 kHz.
Fs = 8000;
N = 205;
lo = sin(2*pi*697*(0:N-1)/Fs);
hi = sin(2*pi*1209*(0:N-1)/Fs);
data = lo + hi;

% Use the Goertzel algorithm to compute the DFT of the tone.
% Choose the indices corresponding to the frequencies used to generate the numbers 0 through 9.
f = [697 770 852 941 1209 1336 1477];
freq_indices = round(f/Fs*N);
my_dft_data = my_goertzel(data,freq_indices)

% The answer
dft_data = goertzel(data, freq_indices + 1)
pavel_dft_data = pavel_goertzel(data, freq_indices)

% Plot the DFT magnitude.
% figure('Name', 'My DFT Magnitude')
% stem(f,abs(my_dft_data))

figure('Name', 'Pavel''s DFT Magnitude')
stem(f, abs(pavel_dft_data))

ax = gca;
ax.XTick = f;
xlabel('Frequency (Hz)')
title('DFT Magnitude')